name: MIKEHARDIE.NET
favicon: null
layout_spectrum: 0.21893784613348544
typography_spectrum: 0.6259788144379854
title: 'The way it was, is and is to come...'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5307643353007734
  lightness: 0.7834238200448453
  saturation: 0.522218873957172
  rhythmicContrast: 0.6859682758804411
purpose: []
