name: MIKEHARDIE.NET
favicon: null
layout_spectrum: 1
typography_spectrum: 0.42653
title: 'The way it was, is and is to come...'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#cecece'
    - '#929292'
    - '#6a6a6a'
  brandStrength: 0.5307643353007734
  lightness: 0.7834238200448453
  saturation: 0.522218873957172
  rhythmicContrast: 0.6859682758804411
purpose: []
